CREATE TABLE public.BATCH_JOB_EXECUTION (
  JOB_EXECUTION_ID BIGINT NOT NULL,
  VERSION BIGINT,
  JOB_INSTANCE_ID BIGINT NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL,
  START_TIME TIMESTAMP,
  END_TIME TIMESTAMP,
  STATUS VARCHAR(10),
  EXIT_CODE VARCHAR(2500),
  EXIT_MESSAGE VARCHAR(2500),
  LAST_UPDATED TIMESTAMP
);
COMMENT ON table public.BATCH_JOB_EXECUTION is 'バッチジョブ実行';
COMMENT ON column public.BATCH_JOB_EXECUTION.JOB_EXECUTION_ID is 'ジョブ実行ID';
COMMENT ON column public.BATCH_JOB_EXECUTION.VERSION is 'バージョン番号';
COMMENT ON column public.BATCH_JOB_EXECUTION.JOB_INSTANCE_ID is 'ジョブインスタンスID';
COMMENT ON column public.BATCH_JOB_EXECUTION.CREATE_TIME is '作成日時';
COMMENT ON column public.BATCH_JOB_EXECUTION.START_TIME is '開始日時';
COMMENT ON column public.BATCH_JOB_EXECUTION.END_TIME is '終了日時';
COMMENT ON column public.BATCH_JOB_EXECUTION.STATUS is 'ステータス';
COMMENT ON column public.BATCH_JOB_EXECUTION.EXIT_CODE is '終了コード';
COMMENT ON column public.BATCH_JOB_EXECUTION.EXIT_MESSAGE is '終了メッセージ';
COMMENT ON column public.BATCH_JOB_EXECUTION.LAST_UPDATED is '最終更新日時';
CREATE TABLE public.BATCH_JOB_EXECUTION_CONTEXT (
  JOB_EXECUTION_ID BIGINT NOT NULL,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT TEXT
);
COMMENT ON table public.BATCH_JOB_EXECUTION_CONTEXT is 'バッチジョブ実行コンテキスト';
COMMENT ON column public.BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID is 'ジョブ実行ID';
COMMENT ON column public.BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT is 'ショートコンテキスト';
COMMENT ON column public.BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT is 'シリアライズドコンテキスト';
CREATE TABLE public.BATCH_JOB_EXECUTION_PARAMS (
  JOB_EXECUTION_ID BIGINT NOT NULL,
  PARAMETER_NAME VARCHAR(100) NOT NULL,
  PARAMETER_TYPE VARCHAR(100) NOT NULL,
  PARAMETER_VALUE VARCHAR(2500),
  IDENTIFYING CHAR(1) NOT NULL
);
COMMENT ON table public.BATCH_JOB_EXECUTION_PARAMS is 'バッチジョブ実行パラメータ';
COMMENT ON column public.BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID is 'ジョブ実行ID';
COMMENT ON column public.BATCH_JOB_EXECUTION_PARAMS.PARAMETER_NAME is 'パラメータ名';
COMMENT ON column public.BATCH_JOB_EXECUTION_PARAMS.PARAMETER_TYPE is 'データ型';
COMMENT ON column public.BATCH_JOB_EXECUTION_PARAMS.PARAMETER_VALUE is 'パラメータ値';
COMMENT ON column public.BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING is '一意識別フラグ';
CREATE TABLE public.BATCH_JOB_INSTANCE (
  JOB_INSTANCE_ID BIGINT NOT NULL,
  VERSION BIGINT,
  JOB_NAME VARCHAR(100) NOT NULL,
  JOB_KEY VARCHAR(32) NOT NULL
);
COMMENT ON table public.BATCH_JOB_INSTANCE is 'バッチジョブインスタンス';
COMMENT ON column public.BATCH_JOB_INSTANCE.JOB_INSTANCE_ID is 'ジョブインスタンスID';
COMMENT ON column public.BATCH_JOB_INSTANCE.VERSION is 'バージョン番号';
COMMENT ON column public.BATCH_JOB_INSTANCE.JOB_NAME is 'ジョブ名';
COMMENT ON column public.BATCH_JOB_INSTANCE.JOB_KEY is 'ジョブキー';
CREATE TABLE public.BATCH_STEP_EXECUTION (
  STEP_EXECUTION_ID BIGINT NOT NULL,
  VERSION BIGINT NOT NULL,
  STEP_NAME VARCHAR(100) NOT NULL,
  JOB_EXECUTION_ID BIGINT NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL,
  START_TIME TIMESTAMP,
  END_TIME TIMESTAMP,
  STATUS VARCHAR(10),
  COMMIT_COUNT BIGINT,
  READ_COUNT BIGINT,
  FILTER_COUNT BIGINT,
  WRITE_COUNT BIGINT,
  READ_SKIP_COUNT BIGINT,
  WRITE_SKIP_COUNT BIGINT,
  PROCESS_SKIP_COUNT BIGINT,
  ROLLBACK_COUNT BIGINT,
  EXIT_CODE VARCHAR(2500),
  EXIT_MESSAGE VARCHAR(2500),
  LAST_UPDATED TIMESTAMP
);
COMMENT ON table public.BATCH_STEP_EXECUTION is 'バッチステップ実行';
COMMENT ON column public.BATCH_STEP_EXECUTION.STEP_EXECUTION_ID is 'ステップ実行ID';
COMMENT ON column public.BATCH_STEP_EXECUTION.VERSION is 'バージョン番号';
COMMENT ON column public.BATCH_STEP_EXECUTION.STEP_NAME is 'ステップ名';
COMMENT ON column public.BATCH_STEP_EXECUTION.JOB_EXECUTION_ID is 'ジョブ実行ID';
COMMENT ON column public.BATCH_STEP_EXECUTION.CREATE_TIME is '作成日時';
COMMENT ON column public.BATCH_STEP_EXECUTION.START_TIME is '開始日時';
COMMENT ON column public.BATCH_STEP_EXECUTION.END_TIME is '終了日時';
COMMENT ON column public.BATCH_STEP_EXECUTION.STATUS is 'ステータス';
COMMENT ON column public.BATCH_STEP_EXECUTION.COMMIT_COUNT is 'コミット回数';
COMMENT ON column public.BATCH_STEP_EXECUTION.READ_COUNT is '読み込みデータ件数';
COMMENT ON column public.BATCH_STEP_EXECUTION.FILTER_COUNT is 'フィルタリングデータ件数';
COMMENT ON column public.BATCH_STEP_EXECUTION.WRITE_COUNT is '書込データ件数';
COMMENT ON column public.BATCH_STEP_EXECUTION.READ_SKIP_COUNT is '読込スキップデータ件数';
COMMENT ON column public.BATCH_STEP_EXECUTION.WRITE_SKIP_COUNT is '書込スキップデータ件数';
COMMENT ON column public.BATCH_STEP_EXECUTION.PROCESS_SKIP_COUNT is 'プロセススキップデータ件数';
COMMENT ON column public.BATCH_STEP_EXECUTION.ROLLBACK_COUNT is 'ロールバック回数';
COMMENT ON column public.BATCH_STEP_EXECUTION.EXIT_CODE is '終了コード';
COMMENT ON column public.BATCH_STEP_EXECUTION.EXIT_MESSAGE is '終了メッセージ';
COMMENT ON column public.BATCH_STEP_EXECUTION.LAST_UPDATED is '最終更新日時';
CREATE TABLE public.BATCH_STEP_EXECUTION_CONTEXT (
  STEP_EXECUTION_ID BIGINT NOT NULL,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT TEXT
);
COMMENT ON table public.BATCH_STEP_EXECUTION_CONTEXT is 'バッチステップ実行コンテキスト';
COMMENT ON column public.BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID is 'ステップ実行ID';
COMMENT ON column public.BATCH_STEP_EXECUTION_CONTEXT.SHORT_CONTEXT is 'ショートコンテキスト';
COMMENT ON column public.BATCH_STEP_EXECUTION_CONTEXT.SERIALIZED_CONTEXT is 'シリアライズドコンテキスト';
CREATE TABLE public.BUSINESS_DATE (
  SEGMENT_ID VARCHAR(2) NOT NULL,
  BIZ_DATE VARCHAR(8)
);
COMMENT ON table public.BUSINESS_DATE is '業務日付';
COMMENT ON column public.BUSINESS_DATE.SEGMENT_ID is '区分';
COMMENT ON column public.BUSINESS_DATE.BIZ_DATE is '業務日付';
CREATE TABLE public.CODE_NAME (
  CODE_ID VARCHAR(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  LANG VARCHAR(2) NOT NULL,
  SORT_ORDER VARCHAR(1) NOT NULL,
  CODE_NAME VARCHAR(50) NOT NULL,
  SHORT_NAME VARCHAR(50),
  OPTION01 VARCHAR(40),
  OPTION02 VARCHAR(40),
  OPTION03 VARCHAR(40),
  OPTION04 VARCHAR(40),
  OPTION05 VARCHAR(40),
  OPTION06 VARCHAR(40),
  OPTION07 VARCHAR(40),
  OPTION08 VARCHAR(40),
  OPTION09 VARCHAR(40),
  OPTION10 VARCHAR(40)
);
COMMENT ON table public.CODE_NAME is 'コード名称';
COMMENT ON column public.CODE_NAME.CODE_ID is 'コードID';
COMMENT ON column public.CODE_NAME.CODE_VALUE is 'コード値';
COMMENT ON column public.CODE_NAME.LANG is '言語';
COMMENT ON column public.CODE_NAME.SORT_ORDER is 'ソート順';
COMMENT ON column public.CODE_NAME.CODE_NAME is '名称';
COMMENT ON column public.CODE_NAME.SHORT_NAME is '略称';
COMMENT ON column public.CODE_NAME.OPTION01 is 'オプション名称1';
COMMENT ON column public.CODE_NAME.OPTION02 is 'オプション名称2';
COMMENT ON column public.CODE_NAME.OPTION03 is 'オプション名称3';
COMMENT ON column public.CODE_NAME.OPTION04 is 'オプション名称4';
COMMENT ON column public.CODE_NAME.OPTION05 is 'オプション名称5';
COMMENT ON column public.CODE_NAME.OPTION06 is 'オプション名称6';
COMMENT ON column public.CODE_NAME.OPTION07 is 'オプション名称7';
COMMENT ON column public.CODE_NAME.OPTION08 is 'オプション名称8';
COMMENT ON column public.CODE_NAME.OPTION09 is 'オプション名称9';
COMMENT ON column public.CODE_NAME.OPTION10 is 'オプション名称10';
CREATE TABLE public.CODE_PATTERN (
  CODE_ID VARCHAR(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  LANG VARCHAR(2) NOT NULL,
  PATTERN01 VARCHAR(1) NOT NULL,
  PATTERN02 VARCHAR(1),
  PATTERN03 VARCHAR(1),
  PATTERN04 VARCHAR(1),
  PATTERN05 VARCHAR(1),
  PATTERN06 VARCHAR(1),
  PATTERN07 VARCHAR(1),
  PATTERN08 VARCHAR(1),
  PATTERN09 VARCHAR(1),
  PATTERN10 VARCHAR(1),
  PATTERN11 VARCHAR(1),
  PATTERN12 VARCHAR(1),
  PATTERN13 VARCHAR(1),
  PATTERN14 VARCHAR(1),
  PATTERN15 VARCHAR(1),
  PATTERN16 VARCHAR(1),
  PATTERN17 VARCHAR(1),
  PATTERN18 VARCHAR(1),
  PATTERN19 VARCHAR(1),
  PATTERN20 VARCHAR(1)
);
COMMENT ON table public.CODE_PATTERN is 'コードパターン';
COMMENT ON column public.CODE_PATTERN.CODE_ID is 'コードID';
COMMENT ON column public.CODE_PATTERN.CODE_VALUE is 'コード値';
COMMENT ON column public.CODE_PATTERN.LANG is '言語';
COMMENT ON column public.CODE_PATTERN.PATTERN01 is 'コードパターン1';
COMMENT ON column public.CODE_PATTERN.PATTERN02 is 'コードパターン2';
COMMENT ON column public.CODE_PATTERN.PATTERN03 is 'コードパターン3';
COMMENT ON column public.CODE_PATTERN.PATTERN04 is 'コードパターン4';
COMMENT ON column public.CODE_PATTERN.PATTERN05 is 'コードパターン5';
COMMENT ON column public.CODE_PATTERN.PATTERN06 is 'コードパターン6';
COMMENT ON column public.CODE_PATTERN.PATTERN07 is 'コードパターン7';
COMMENT ON column public.CODE_PATTERN.PATTERN08 is 'コードパターン8';
COMMENT ON column public.CODE_PATTERN.PATTERN09 is 'コードパターン9';
COMMENT ON column public.CODE_PATTERN.PATTERN10 is 'コードパターン10';
COMMENT ON column public.CODE_PATTERN.PATTERN11 is 'コードパターン11';
COMMENT ON column public.CODE_PATTERN.PATTERN12 is 'コードパターン12';
COMMENT ON column public.CODE_PATTERN.PATTERN13 is 'コードパターン13';
COMMENT ON column public.CODE_PATTERN.PATTERN14 is 'コードパターン14';
COMMENT ON column public.CODE_PATTERN.PATTERN15 is 'コードパターン15';
COMMENT ON column public.CODE_PATTERN.PATTERN16 is 'コードパターン16';
COMMENT ON column public.CODE_PATTERN.PATTERN17 is 'コードパターン17';
COMMENT ON column public.CODE_PATTERN.PATTERN18 is 'コードパターン18';
COMMENT ON column public.CODE_PATTERN.PATTERN19 is 'コードパターン19';
COMMENT ON column public.CODE_PATTERN.PATTERN20 is 'コードパターン20';
CREATE TABLE public.MAIL_ATTACHED_FILE (
  MAIL_REQUEST_ID VARCHAR(20) NOT NULL,
  SERIAL_NUMBER INTEGER NOT NULL,
  FILE_NAME VARCHAR(100),
  CONTENT_TYPE VARCHAR(30),
  ATTACHED_FILE BYTEA
);
COMMENT ON table public.MAIL_ATTACHED_FILE is 'メール添付ファイル';
COMMENT ON column public.MAIL_ATTACHED_FILE.MAIL_REQUEST_ID is 'メール送信要求ID';
COMMENT ON column public.MAIL_ATTACHED_FILE.SERIAL_NUMBER is '連番';
COMMENT ON column public.MAIL_ATTACHED_FILE.FILE_NAME is '添付ファイル名';
COMMENT ON column public.MAIL_ATTACHED_FILE.CONTENT_TYPE is 'Content-Type';
COMMENT ON column public.MAIL_ATTACHED_FILE.ATTACHED_FILE is '添付ファイル';
CREATE TABLE public.MAIL_RECIPIENT (
  MAIL_REQUEST_ID VARCHAR(20) NOT NULL,
  SERIAL_NUMBER INTEGER NOT NULL,
  RECIPIENT_TYPE VARCHAR(1),
  MAIL_ADDRESS VARCHAR(256)
);
COMMENT ON table public.MAIL_RECIPIENT is 'メール送信先';
COMMENT ON column public.MAIL_RECIPIENT.MAIL_REQUEST_ID is 'メール送信要求ID';
COMMENT ON column public.MAIL_RECIPIENT.SERIAL_NUMBER is '連番';
COMMENT ON column public.MAIL_RECIPIENT.RECIPIENT_TYPE is '送信先区分';
COMMENT ON column public.MAIL_RECIPIENT.MAIL_ADDRESS is 'メールアドレス';
CREATE TABLE public.MAIL_REQUEST (
  MAIL_REQUEST_ID VARCHAR(20) NOT NULL,
  SUBJECT VARCHAR(100),
  MAIL_FROM VARCHAR(256),
  REPLY_TO VARCHAR(256),
  RETURN_PATH VARCHAR(256),
  CHARSET VARCHAR(20),
  STATUS VARCHAR(1),
  REQUEST_DATETIME TIMESTAMP,
  SEND_DATETIME TIMESTAMP,
  MAIL_BODY VARCHAR(1000)
);
COMMENT ON table public.MAIL_REQUEST is 'メール送信要求';
COMMENT ON column public.MAIL_REQUEST.MAIL_REQUEST_ID is 'メール送信要求ID';
COMMENT ON column public.MAIL_REQUEST.SUBJECT is '件名';
COMMENT ON column public.MAIL_REQUEST.MAIL_FROM is '送信者メールアドレス';
COMMENT ON column public.MAIL_REQUEST.REPLY_TO is '返信先メールアドレス';
COMMENT ON column public.MAIL_REQUEST.RETURN_PATH is '差戻し先メールアドレス';
COMMENT ON column public.MAIL_REQUEST.CHARSET is '文字セット';
COMMENT ON column public.MAIL_REQUEST.STATUS is 'ステータス';
COMMENT ON column public.MAIL_REQUEST.REQUEST_DATETIME is '要求日時';
COMMENT ON column public.MAIL_REQUEST.SEND_DATETIME is '送信日時';
COMMENT ON column public.MAIL_REQUEST.MAIL_BODY is '本文';
CREATE TABLE public.MAIL_TEMPLATE (
  MAIL_TEMPLATE_ID VARCHAR(10) NOT NULL,
  LANG VARCHAR(2) NOT NULL,
  SUBJECT VARCHAR(100),
  CHARSET VARCHAR(20),
  MAIL_BODY VARCHAR(1000)
);
COMMENT ON table public.MAIL_TEMPLATE is 'メールテンプレート';
COMMENT ON column public.MAIL_TEMPLATE.MAIL_TEMPLATE_ID is 'メールテンプレートID';
COMMENT ON column public.MAIL_TEMPLATE.LANG is '言語';
COMMENT ON column public.MAIL_TEMPLATE.SUBJECT is '件名';
COMMENT ON column public.MAIL_TEMPLATE.CHARSET is '文字セット';
COMMENT ON column public.MAIL_TEMPLATE.MAIL_BODY is '本文';
CREATE TABLE public.ORGANIZATION (
  ORGANIZATION_ID SERIAL NOT NULL,
  ORGANIZATION_NAME VARCHAR(128),
  UPPER_ORGANIZATION INTEGER
);
COMMENT ON table public.ORGANIZATION is '組織';
COMMENT ON column public.ORGANIZATION.ORGANIZATION_ID is '組織ID';
COMMENT ON column public.ORGANIZATION.ORGANIZATION_NAME is '組織名';
COMMENT ON column public.ORGANIZATION.UPPER_ORGANIZATION is '上位組織ID';
CREATE TABLE public.PROJECT (
  PROJECT_ID SERIAL NOT NULL,
  PROJECT_NAME VARCHAR(128) NOT NULL,
  PROJECT_TYPE VARCHAR(2) NOT NULL,
  PROJECT_CLASS VARCHAR(2) NOT NULL,
  PROJECT_START_DATE DATE NOT NULL,
  PROJECT_END_DATE DATE NOT NULL,
  ORGANIZATION_ID INTEGER NOT NULL,
  CLIENT_ID INTEGER NOT NULL,
  PROJECT_MANAGER VARCHAR(128) NOT NULL,
  PROJECT_LEADER VARCHAR(128) NOT NULL,
  NOTE VARCHAR(512),
  SALES INTEGER,
  VERSION_NO BIGINT NOT NULL DEFAULT 1
);
COMMENT ON table public.PROJECT is 'プロジェクト';
COMMENT ON column public.PROJECT.PROJECT_ID is 'プロジェクトID';
COMMENT ON column public.PROJECT.PROJECT_NAME is 'プロジェクト名';
COMMENT ON column public.PROJECT.PROJECT_TYPE is 'プロジェクト種別';
COMMENT ON column public.PROJECT.PROJECT_CLASS is 'プロジェクト分類';
COMMENT ON column public.PROJECT.PROJECT_START_DATE is 'プロジェクト開始日付';
COMMENT ON column public.PROJECT.PROJECT_END_DATE is 'プロジェクト終了日付';
COMMENT ON column public.PROJECT.ORGANIZATION_ID is '組織ID';
COMMENT ON column public.PROJECT.CLIENT_ID is '顧客ID';
COMMENT ON column public.PROJECT.PROJECT_MANAGER is 'プロジェクトマネージャー';
COMMENT ON column public.PROJECT.PROJECT_LEADER is 'プロジェクトリーダー';
COMMENT ON column public.PROJECT.NOTE is '備考';
COMMENT ON column public.PROJECT.SALES is '売上高';
COMMENT ON column public.PROJECT.VERSION_NO is 'バージョン番号';
CREATE TABLE public.PROJECTS_BY_USER (
  USER_ID SERIAL NOT NULL,
  REQUEST_ID BIGINT,
  FILE_NAME VARCHAR(50),
  CREATE_DATETIME TIMESTAMP,
  EXPIRE_DATETIME TIMESTAMP
);
COMMENT ON table public.PROJECTS_BY_USER is 'ユーザ別従事プロジェクト';
COMMENT ON column public.PROJECTS_BY_USER.USER_ID is 'ユーザID';
COMMENT ON column public.PROJECTS_BY_USER.REQUEST_ID is '要求ID';
COMMENT ON column public.PROJECTS_BY_USER.FILE_NAME is 'ファイル名';
COMMENT ON column public.PROJECTS_BY_USER.CREATE_DATETIME is '作成日時';
COMMENT ON column public.PROJECTS_BY_USER.EXPIRE_DATETIME is '有効期限';
CREATE TABLE public.PROJECTS_BY_USER_REQUEST (
  ID BIGSERIAL NOT NULL,
  STATUS VARCHAR(2) NOT NULL,
  REQUEST_DATETIME TIMESTAMP NOT NULL,
  USER_ID INTEGER NOT NULL
);
COMMENT ON table public.PROJECTS_BY_USER_REQUEST is 'ユーザ別従事プロジェクト作成要求';
COMMENT ON column public.PROJECTS_BY_USER_REQUEST.ID is 'ID';
COMMENT ON column public.PROJECTS_BY_USER_REQUEST.STATUS is 'ステータス';
COMMENT ON column public.PROJECTS_BY_USER_REQUEST.REQUEST_DATETIME is '要求日時';
COMMENT ON column public.PROJECTS_BY_USER_REQUEST.USER_ID is 'ユーザID';
CREATE TABLE public.PROJECT_USER (
  PROJECT_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL
);
COMMENT ON table public.PROJECT_USER is 'プロジェクト担当者';
COMMENT ON column public.PROJECT_USER.PROJECT_ID is 'プロジェクトID';
COMMENT ON column public.PROJECT_USER.USER_ID is 'ユーザID';
CREATE TABLE public.PROJECT_WORK (
  PROJECT_WORK_ID SERIAL NOT NULL,
  PROJECT_ID INTEGER,
  PROJECT_NAME VARCHAR(128) NOT NULL,
  PROJECT_TYPE VARCHAR(2) NOT NULL,
  PROJECT_CLASS VARCHAR(2) NOT NULL,
  PROJECT_START_DATE DATE NOT NULL,
  PROJECT_END_DATE DATE NOT NULL,
  ORGANIZATION_ID INTEGER NOT NULL,
  CLIENT_ID INTEGER NOT NULL,
  PROJECT_MANAGER VARCHAR(128) NOT NULL,
  PROJECT_LEADER VARCHAR(128) NOT NULL,
  NOTE VARCHAR(512),
  SALES INTEGER
);
COMMENT ON table public.PROJECT_WORK is 'プロジェクトワーク';
COMMENT ON column public.PROJECT_WORK.PROJECT_WORK_ID is 'プロジェクトワークID';
COMMENT ON column public.PROJECT_WORK.PROJECT_ID is 'プロジェクトID';
COMMENT ON column public.PROJECT_WORK.PROJECT_NAME is 'プロジェクト名';
COMMENT ON column public.PROJECT_WORK.PROJECT_TYPE is 'プロジェクト種別';
COMMENT ON column public.PROJECT_WORK.PROJECT_CLASS is 'プロジェクト分類';
COMMENT ON column public.PROJECT_WORK.PROJECT_START_DATE is 'プロジェクト開始日付';
COMMENT ON column public.PROJECT_WORK.PROJECT_END_DATE is 'プロジェクト終了日付';
COMMENT ON column public.PROJECT_WORK.ORGANIZATION_ID is '組織ID';
COMMENT ON column public.PROJECT_WORK.CLIENT_ID is '顧客ID';
COMMENT ON column public.PROJECT_WORK.PROJECT_MANAGER is 'プロジェクトマネージャー';
COMMENT ON column public.PROJECT_WORK.PROJECT_LEADER is 'プロジェクトリーダー';
COMMENT ON column public.PROJECT_WORK.NOTE is '備考';
COMMENT ON column public.PROJECT_WORK.SALES is '売上高';
CREATE TABLE public.RESIDENT_BATCH_STATE (
  JOB_ID VARCHAR(20) NOT NULL,
  RUNNING BOOLEAN
);
COMMENT ON table public.RESIDENT_BATCH_STATE is '常駐バッチ状態管理';
COMMENT ON column public.RESIDENT_BATCH_STATE.JOB_ID is 'ジョブID';
COMMENT ON column public.RESIDENT_BATCH_STATE.RUNNING is '実行フラグ';
CREATE TABLE public.SPRING_SESSION (
  PRIMARY_ID CHAR(36) NOT NULL,
  SESSION_ID CHAR(36) NOT NULL,
  CREATION_TIME BIGINT NOT NULL,
  LAST_ACCESS_TIME BIGINT NOT NULL,
  MAX_INACTIVE_INTERVAL INTEGER NOT NULL,
  EXPIRY_TIME BIGINT NOT NULL,
  PRINCIPAL_NAME VARCHAR(100)
);
COMMENT ON table public.SPRING_SESSION is 'Springセッション';
COMMENT ON column public.SPRING_SESSION.PRIMARY_ID is 'プライマリーID';
COMMENT ON column public.SPRING_SESSION.SESSION_ID is 'セッションID';
COMMENT ON column public.SPRING_SESSION.CREATION_TIME is '作成日時';
COMMENT ON column public.SPRING_SESSION.LAST_ACCESS_TIME is '最終アクセス日時';
COMMENT ON column public.SPRING_SESSION.MAX_INACTIVE_INTERVAL is '最大非活性時間';
COMMENT ON column public.SPRING_SESSION.EXPIRY_TIME is '有効期限';
COMMENT ON column public.SPRING_SESSION.PRINCIPAL_NAME is 'プリンシパル名';
CREATE TABLE public.SPRING_SESSION_ATTRIBUTES (
  SESSION_PRIMARY_ID CHAR(36) NOT NULL,
  ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
  ATTRIBUTE_BYTES BYTEA NOT NULL
);
COMMENT ON table public.SPRING_SESSION_ATTRIBUTES is 'Springセッション属性';
COMMENT ON column public.SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID is 'セッションプライマリID';
COMMENT ON column public.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME is '属性名';
COMMENT ON column public.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES is '属性値';
CREATE TABLE public.SYSTEM_ACCOUNT (
  USER_ID INTEGER NOT NULL,
  LOGIN_ID VARCHAR(20) NOT NULL,
  USER_PASSWORD VARCHAR(64) NOT NULL,
  PASSWORD_EXPIRATION_DATE DATE NOT NULL,
  FAILED_COUNT SMALLINT NOT NULL,
  EFFECTIVE_DATE_FROM DATE,
  EFFECTIVE_DATE_TO DATE,
  LAST_LOGIN_DATE_TIME TIMESTAMP(6)
);
COMMENT ON table public.SYSTEM_ACCOUNT is 'システムアカウント';
COMMENT ON column public.SYSTEM_ACCOUNT.USER_ID is 'ユーザID';
COMMENT ON column public.SYSTEM_ACCOUNT.LOGIN_ID is 'ログインID';
COMMENT ON column public.SYSTEM_ACCOUNT.USER_PASSWORD is 'パスワード';
COMMENT ON column public.SYSTEM_ACCOUNT.PASSWORD_EXPIRATION_DATE is 'パスワード有効期限';
COMMENT ON column public.SYSTEM_ACCOUNT.FAILED_COUNT is '認証失敗回数';
COMMENT ON column public.SYSTEM_ACCOUNT.EFFECTIVE_DATE_FROM is '有効期限(FROM)';
COMMENT ON column public.SYSTEM_ACCOUNT.EFFECTIVE_DATE_TO is '有効期限(TO)';
COMMENT ON column public.SYSTEM_ACCOUNT.LAST_LOGIN_DATE_TIME is '最終ログイン日時';
CREATE TABLE public.USERS (
  USER_ID SERIAL NOT NULL,
  KANJI_NAME VARCHAR(128) NOT NULL,
  KANA_NAME VARCHAR(128) NOT NULL,
  PM_FLAG BOOLEAN NOT NULL
);
COMMENT ON table public.USERS is 'ユーザ';
COMMENT ON column public.USERS.USER_ID is 'ユーザID';
COMMENT ON column public.USERS.KANJI_NAME is '漢字氏名';
COMMENT ON column public.USERS.KANA_NAME is 'ふりがな';
COMMENT ON column public.USERS.PM_FLAG is 'PM職フラグ';
CREATE INDEX IX_SPRING_SESSION_EXPIRY_TIME ON public.SPRING_SESSION
(
  EXPIRY_TIME
);CREATE INDEX IX_SPRING_SESSION_PRINCIPAL_NAME ON public.SPRING_SESSION
(
  PRINCIPAL_NAME
);ALTER TABLE public.BATCH_JOB_EXECUTION ADD CONSTRAINT PK_BATCH_JOB_EXECUTION PRIMARY KEY
(
  JOB_EXECUTION_ID
);ALTER TABLE public.BATCH_JOB_EXECUTION_CONTEXT ADD CONSTRAINT PK_BATCH_JOB_EXECUTION_CONTEXT PRIMARY KEY
(
  JOB_EXECUTION_ID
);ALTER TABLE public.BATCH_JOB_INSTANCE ADD CONSTRAINT PK_BATCH_JOB_INSTANCE PRIMARY KEY
(
  JOB_INSTANCE_ID
);ALTER TABLE public.BATCH_STEP_EXECUTION ADD CONSTRAINT PK_BATCH_STEP_EXECUTION PRIMARY KEY
(
  STEP_EXECUTION_ID
);ALTER TABLE public.BATCH_STEP_EXECUTION_CONTEXT ADD CONSTRAINT PK_BATCH_STEP_EXECUTION_CONTEXT PRIMARY KEY
(
  STEP_EXECUTION_ID
);ALTER TABLE public.BUSINESS_DATE ADD CONSTRAINT PK_BUSINESS_DATE PRIMARY KEY
(
  SEGMENT_ID
);ALTER TABLE public.RESIDENT_BATCH_STATE ADD CONSTRAINT PK_BUSINESS_DATE1 PRIMARY KEY
(
  JOB_ID
);ALTER TABLE public.CODE_NAME ADD CONSTRAINT PK_CODE_NAME PRIMARY KEY
(
  CODE_ID,
  CODE_VALUE,
  LANG
);ALTER TABLE public.CODE_PATTERN ADD CONSTRAINT PK_CODE_PATTERN PRIMARY KEY
(
  CODE_ID,
  CODE_VALUE,
  LANG
);ALTER TABLE public.MAIL_ATTACHED_FILE ADD CONSTRAINT PK_MAIL_ATTACHED_FILE PRIMARY KEY
(
  MAIL_REQUEST_ID,
  SERIAL_NUMBER
);ALTER TABLE public.MAIL_RECIPIENT ADD CONSTRAINT PK_MAIL_RECIPIENT PRIMARY KEY
(
  MAIL_REQUEST_ID,
  SERIAL_NUMBER
);ALTER TABLE public.MAIL_REQUEST ADD CONSTRAINT PK_MAIL_REQUEST PRIMARY KEY
(
  MAIL_REQUEST_ID
);ALTER TABLE public.MAIL_TEMPLATE ADD CONSTRAINT PK_MAIL_TEMPLATE PRIMARY KEY
(
  MAIL_TEMPLATE_ID,
  LANG
);ALTER TABLE public.ORGANIZATION ADD CONSTRAINT PK_ORGANIZATION PRIMARY KEY
(
  ORGANIZATION_ID
);ALTER TABLE public.PROJECT ADD CONSTRAINT PK_PROJECT PRIMARY KEY
(
  PROJECT_ID
);ALTER TABLE public.PROJECTS_BY_USER ADD CONSTRAINT PK_PROJECTS_BY_USER PRIMARY KEY
(
  USER_ID
);ALTER TABLE public.PROJECTS_BY_USER_REQUEST ADD CONSTRAINT PK_PROJECTS_BY_USER_REQUEST PRIMARY KEY
(
  ID
);ALTER TABLE public.PROJECT_USER ADD CONSTRAINT PK_PROJECT_USER PRIMARY KEY
(
  PROJECT_ID,
  USER_ID
);ALTER TABLE public.PROJECT_WORK ADD CONSTRAINT PK_PROJECT_WORK PRIMARY KEY
(
  PROJECT_WORK_ID
);ALTER TABLE public.SPRING_SESSION ADD CONSTRAINT PK_SPRING_SESSION PRIMARY KEY
(
  PRIMARY_ID
);ALTER TABLE public.SPRING_SESSION_ATTRIBUTES ADD CONSTRAINT PK_SPRING_SESSION_ATTRIBUTES PRIMARY KEY
(
  SESSION_PRIMARY_ID,
  ATTRIBUTE_NAME
);ALTER TABLE public.USERS ADD CONSTRAINT PK_USERS PRIMARY KEY
(
  USER_ID
);ALTER TABLE public.SYSTEM_ACCOUNT ADD CONSTRAINT PK__SYSTEM_ACCOUNT PRIMARY KEY
(
  USER_ID
);ALTER TABLE public.BATCH_JOB_INSTANCE ADD CONSTRAINT UQ_BATCH_JOB_INSTANCE_JOB_NAME_JOB_KEY UNIQUE
(
  JOB_NAME,
  JOB_KEY
);CREATE UNIQUE INDEX UQ_SPRING_SESSION_SESSION_ID ON public.SPRING_SESSION
(
  SESSION_ID
);ALTER TABLE public.SYSTEM_ACCOUNT ADD CONSTRAINT UQ_SYSTEM_ACCOUNT_LOGIN_ID UNIQUE
(
  LOGIN_ID
);ALTER TABLE public.BATCH_JOB_EXECUTION
ADD 
FOREIGN KEY (
  JOB_INSTANCE_ID
) REFERENCES public.BATCH_JOB_INSTANCE (
  JOB_INSTANCE_ID
);
ALTER TABLE public.BATCH_JOB_EXECUTION_CONTEXT
ADD 
FOREIGN KEY (
  JOB_EXECUTION_ID
) REFERENCES public.BATCH_JOB_EXECUTION (
  JOB_EXECUTION_ID
);
ALTER TABLE public.BATCH_JOB_EXECUTION_PARAMS
ADD 
FOREIGN KEY (
  JOB_EXECUTION_ID
) REFERENCES public.BATCH_JOB_EXECUTION (
  JOB_EXECUTION_ID
);
ALTER TABLE public.BATCH_STEP_EXECUTION
ADD 
FOREIGN KEY (
  JOB_EXECUTION_ID
) REFERENCES public.BATCH_JOB_EXECUTION (
  JOB_EXECUTION_ID
);
ALTER TABLE public.BATCH_STEP_EXECUTION_CONTEXT
ADD 
FOREIGN KEY (
  STEP_EXECUTION_ID
) REFERENCES public.BATCH_STEP_EXECUTION (
  STEP_EXECUTION_ID
);
ALTER TABLE public.CODE_PATTERN
ADD 
FOREIGN KEY (
  CODE_ID,
  CODE_VALUE,
  LANG
) REFERENCES public.CODE_NAME (
  CODE_ID,
  CODE_VALUE,
  LANG
);
ALTER TABLE public.MAIL_ATTACHED_FILE
ADD 
FOREIGN KEY (
  MAIL_REQUEST_ID
) REFERENCES public.MAIL_REQUEST (
  MAIL_REQUEST_ID
);
ALTER TABLE public.MAIL_RECIPIENT
ADD 
FOREIGN KEY (
  MAIL_REQUEST_ID
) REFERENCES public.MAIL_REQUEST (
  MAIL_REQUEST_ID
);
ALTER TABLE public.PROJECT
ADD 
FOREIGN KEY (
  ORGANIZATION_ID
) REFERENCES public.ORGANIZATION (
  ORGANIZATION_ID
);
ALTER TABLE public.PROJECTS_BY_USER
ADD 
FOREIGN KEY (
  REQUEST_ID
) REFERENCES public.PROJECTS_BY_USER_REQUEST (
  ID
);
ALTER TABLE public.PROJECTS_BY_USER
ADD 
FOREIGN KEY (
  USER_ID
) REFERENCES public.USERS (
  USER_ID
);
ALTER TABLE public.PROJECTS_BY_USER_REQUEST
ADD 
FOREIGN KEY (
  USER_ID
) REFERENCES public.USERS (
  USER_ID
);
ALTER TABLE public.PROJECT_USER
ADD 
FOREIGN KEY (
  USER_ID
) REFERENCES public.USERS (
  USER_ID
);
ALTER TABLE public.PROJECT_USER
ADD 
FOREIGN KEY (
  PROJECT_ID
) REFERENCES public.PROJECT (
  PROJECT_ID
);
ALTER TABLE public.SPRING_SESSION_ATTRIBUTES
ADD 
FOREIGN KEY (
  SESSION_PRIMARY_ID
) REFERENCES public.SPRING_SESSION (
  PRIMARY_ID
);
ALTER TABLE public.SYSTEM_ACCOUNT
ADD 
FOREIGN KEY (
  USER_ID
) REFERENCES public.USERS (
  USER_ID
);
